"""changed field 'id' to 'user_id'

Revision ID: 084b9fe3a95a
Revises: 0e0d35e121d3
Create Date: 2025-05-06 01:02:18.850408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "084b9fe3a95a"
down_revision: Union[str, None] = "0e0d35e121d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id', new_column_name='user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id', new_column_name='id')
    # ### end Alembic commands ###
