"""add autoincrement to user_id and drop id

Revision ID: dd043930987d
Revises: 61e8a42457e7
Create Date: 2025-03-02 00:31:23.693827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd043930987d"
down_revision: Union[str, None] = "61e8a42457e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_user", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_user",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
